# This is a basic workflow to help you get started with Actions

name: codepush

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]
    branches:
      - not_now


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codepush:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged
      && github.head_ref != 'develop'
      && !startsWith(github.head_ref, 'release')

    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4

      - name: Init node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.17.6'

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Write npmrc
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          npm config set @pilltong-dev:registry=https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{secrets.GIT_HUB_TOKEN}}  
        
      - name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn

      - name: Push
        run: echo push